dist: trusty
language: shell

services:
  - docker

env:
  jobs:
    - PHP_VERSION=7.2
    - PHP_VERSION=7.3
    - PHP_VERSION=7.4

script:
  - docker-compose run --rm app composer build

after_script:
  - docker-compose down --volumes

notifications:
  slack:
    secure: FHPbVXHOrXsk80e0+WLID8v5m9S59/qoQyM5XK2hytFUaT+oSh0iY+Ajdnajpl+6qd6iQNbREfd04A2TTBxh7+LzHgOqxhHoZSYTgTHgsOPQPgUCxPJpWInwQGxgp+23pE0l+oX8u0lWkYk9NIf+WtrF6niLvT0KLOJiuB8ojms=
