language: php

php:
  - 7
  - 7.1
  - 7.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install

script:
  - composer build

notifications:
  slack:
    secure: FHPbVXHOrXsk80e0+WLID8v5m9S59/qoQyM5XK2hytFUaT+oSh0iY+Ajdnajpl+6qd6iQNbREfd04A2TTBxh7+LzHgOqxhHoZSYTgTHgsOPQPgUCxPJpWInwQGxgp+23pE0l+oX8u0lWkYk9NIf+WtrF6niLvT0KLOJiuB8ojms=
