name: CI

on:
  push:
    branches:
     - master
  pull_request:
    branches:
     - master
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  build:
    name: 'PHP ${{ matrix.php }}'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - '8.1'
          - '8.2'
          - '8.3'

    steps:
      - uses: actions/checkout@v4

      - name: Build
        env:
          PHP_VERSION: ${{matrix.php}}
        run: docker compose run --rm app composer build

      - name: Cleanup
        if: ${{ always() }}
        run: docker compose down --volumes
