name: CI

on:
  push:
    branches:
     - master
  pull_request:
    branches:
     - master
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - 7.3
          - 7.4
          - "8.0"

    steps:
      - uses: actions/checkout@v2

      - name: Build
        env:
          PHP_VERSION: ${{matrix.php}}
        run: docker-compose run --rm app composer build

      - name: Cleanup
        if: ${{ always() }}
        run: docker-compose down --volumes
